configuration: fix error handling of keys missing a '.'
zephyrproject-rtos/west pull request #603
Opened 2022-09-08 04:36 UTC by marc-hb

Fixes #600

De-duplicate the `option.split('.', 1)` "parsing" code into a new, minimalistic and centralized `_InternalCF.SectionKey` class. Add two lines of error handling in this new class in order to provide a meaningful error message. Instead of this cryptic and context free error when invoking `west config --global key_missing_a_dot`:

```
    ...
    File "/usr/lib/python3.10/site-packages/west/configuration.py", in _get
    section, key = option.split('.', 1)
    ValueError: not enough values to unpack (expected 2, got 1)
```

The user now gets this:

```
    ...
    File "/usr/lib/python3.10/site-packages/west/configuration.py", in _get
        raise MalformedConfig(f"Invalid key name: '{dotted_key}'")
     west.configuration.MalformedConfig: Invalid key name: 'key_missing_a_dot'
```

A full stack trace is still printed but now there's useful information at the bottom of it.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2022-09-12 20:08 UTC, mbolivar-nordic requested changes
I think a class is overkill since we don't need these object saround. It would also IMO be cleaner to do this validation in config.py instead of at the API level in configuration.py, so we don't have to dump stack. https://github.com/zephyrproject-rtos/west/pull/604

If you want to keep this PR, can you please raise ValueError instead, and replace the SectionKey class with a method that just returns a 2-tuple instead? I'd be happy to merge that too.

2022-09-12 20:21 UTC, marc-hb commented
I'm really not a fan of OO but the class would have made it easy to add other checks later if needed and right now the class has barely more lines of codes than a function raising the same exception.

I doubt this check is still required after your #604. "Defensive programming" is great... up to a point, maybe we can also assume that `configuration.py` and `config.py` in the same software trust each other? Bugs aside, will there be any code path that could lead to a dot-free `option` here once #604 is merged?

If the check and exception are not required then I will abandon this. I don't think the tiny and localized `option.split` duplication is worth a one-line function.

2022-09-13 15:31 UTC, mbolivar-nordic commented
> the class would have made it easy to add other checks later if needed

So would a function.

> right now the class has barely more lines of codes than a function raising the same exception

But it's not idiomatic Python in my opinion. Allocating a temporary object just to run a method on it and then throw it away is just weird when you can just define a function or method and call it.

> maybe we can also assume that configuration.py and config.py in the same software trust each other?

West is designed as a set of libraries that are used by the main command line application, extension commands, and other third party scripts. The config.py file is a built in command implementation. The configuration.py file is an API implementation. Their purposes are different. It's fine for APIs to barf an exception if you violate their contracts. It's not fine for a command to barf an exception on expected errors like invalid inputs.

> Bugs aside, will there be any code path that could lead to a dot-free option here once https://github.com/zephyrproject-rtos/west/pull/604 is merged?

I hope the above explanation clears this up for you.

> I don't think the tiny and localized option.split duplication is worth a one-line function.

... but it is worth a class, somehow?

2022-09-13 18:02 UTC, marc-hb commented
> The config.py file is a built in command implementation. The configuration.py file is an API implementation.

Thanks, I forgot about API usage! I will resubmit.

> But it's not idiomatic Python in my opinion. Allocating a temporary object just to run a method on it and then throw it away is just weird when you can just define a function or method and call it.

I think it's common for parsers to construct objects in any language. Constructors ensure the output either exists or not; that you never return something incomplete or inconsistent which is typical with a more imperative style. Throwing objects away does not bother me, it's not different from returning tuples or lists (which are of course objects too)

Anyway this does not matter as long as this is merely looking for one dot '.' in a single string, I will switch to a function. Interesting codestyle discussion still.

> > **If the check and exception are not required then I will abandon this.**  I don't think the tiny and localized option.split duplication is worth a one-line function.

> ... but it is worth a class, somehow?

Neither. You took this sentence totally out of its context ("IF check/exception NOT required...") 

After too much Java exposure I've become a huge fan of http://steve-yegge.blogspot.com/2006/03/execution-in-kingdom-of-nouns.html but maybe I've just met my match :-) Didn't expect that considering the number of (admittedly persistent!) classes in west...

2022-09-14 00:39 UTC, mbolivar-nordic commented
> I have never considered Python to be heavily influenced by functional languages, no matter what people say or think. - Guido Van Rossum

That's referring to https://en.wikipedia.org/wiki/Functional_programming, not whether or not we use a function! Any class definition is full of functions in the form of methods.

2022-09-14 00:40 UTC, mbolivar-nordic commented
> If you want to keep this PR, can you please raise ValueError instead, and replace the SectionKey class with a method that just returns a 2-tuple instead? I'd be happy to merge that too.

So I'm assuming we're going with something like this in a future update, right?

2022-09-14 02:34 UTC, marc-hb commented
> So I'm assuming we're going with something like this in a future update, right?

Sounds good.

> That's referring to https://en.wikipedia.org/wiki/Functional_programming, not whether or not we use a function!

Yes that was even more off-topic that the rest. Well, it's not like we're spamming many people here :-)

My point was just: Python is much more "object-oriented" than "the opposite". Unlike Java, that does not mean everything has to be class.

> Any class definition is full of functions in the form of methods.

... yet that's definitely not what people would refer to as "functional programming", agreed.

2022-09-21 23:46 UTC, mbolivar-nordic approved these changes

2022-09-21 23:46 UTC, merged