commands: add the 'sdk' command to manage SDK.
zephyrproject-rtos/west pull request #722
Opened 2024-07-21 23:56 UTC by soburi

'west sdk' command can list and install SDK.

Run 'west sdk --install=latest' to simply install the latest SDK or
'west sdk' show installed SDKs informations.

This command is just a wrapper for SDK's setup command.
But this command makes the SDK install process simple.
It will be a good improvement for onboarding first-time users.

--

By introducing this command, you no longer need to check the SDK installation procedure to install the SDK,
so I think this will improve the experience for first-time users.

It depends on the SDK-NG installer and GitHub API,
but I think these are stable enough that I don't think it will be a big problem.

2024-07-22 08:29 UTC, pdgendt commented
I think this belongs in the `zephyr` project instead of `west`.

2024-07-22 16:32 UTC, marc-hb requested changes
This definitely belongs to `zephyr/scripts/west_commands`. West is trying to become less and less Zephyr-specific and the Zephyr SDK is obviously Zephyr-specific.

2024-07-22 18:02 UTC, marc-hb commented on src/west/app/project.py
> +find_package(Zephyr-sdk 0.0.0 EXACT QUIET CONFIG PATHS ${zephyr_sdk_search_paths})
@stephanosio , @tejlmand , FYI.

2024-07-24 13:36 UTC, closed without merging

2024-07-25 03:35 UTC, soburi commented
@pdgendt @marc-hb 

Thank you for your opinions

I've recreated this for the Zephyr repository.
https://github.com/zephyrproject-rtos/zephyr/pull/76283