app: more versatile initialization for path in config
zephyrproject-rtos/west pull request #775
Opened 2024-12-18 14:12 UTC by fouge

in case a manifest file is contained into some sub directories, the command to init a workspace locally should be
```
west init -l sub1/sub2 --mf west.yml
```

but in that case, the west top dir is going to be into `sub1` which is an issue.

one workaround is to use:
```
west init -l sub1 --mf sub2/west.yml
```

but in that case, the config is initialized incorrectly: `manifest.path` contains only `sub1` and `manifest.file` is `sub2/west.yml`.

`manifest.path` should contain a path, even if `--mf` is a relative path. `manifest.file` should only contain the filename.

this change allows any usage so that the workspace top dir is created next to `sub1` and the manifest repo can be located into nested directories

fixes #774

2024-12-18 14:17 UTC, fouge commented
IMO to go even further, I think `directory` should point to the location of the west top dir
not: 
> .west is created next to  "directory"

but
> `.west is created in "directory"`

the command would become 
```
west init --mf sub1/sub2/west.yml .
```

thoughts?

2024-12-18 14:54 UTC, fouge commented
@pdgendt tox fails with errors even on `main` on my machine :/

2024-12-18 15:43 UTC, pdgendt commented on src/west/app/project.py
> +        self.config.set('manifest.file', manifest_file.name)
This doesn't allow a nested manifest file, I think? It should be relative to the manifest path.

2024-12-18 18:35 UTC, marc-hb requested changes
Thanks for catching this issue and filing a PR. I haven't time to look at it in detail yet but I already know we _definitely_ need additional test coverage for this. Either adding some new test(s) or tweaking existing tests or a combination of both.

2024-12-18 23:18 UTC, marc-hb commented
Again, thanks for  the excellent report.

> this is a breaking change though, thoughts?

Interestingly, even your very first `west init -l development/west_project1/ --mf west.yml` suggestion at the top would already be a backwards incompatible change.

I'm afraid we need to clearly and formally define the user interface before even looking at the code.

> @pdgendt tox fails with errors even on main on my machine 😞

Please file a separate bug for this. Don't forget the OS and OS version.

2025-10-07 19:35 UTC, marc-hb commented
@fouge please test and review newer 
- #854

2026-01-15 00:04 UTC, marc-hb commented
Superseded by #854

2026-01-15 00:04 UTC, closed without merging